### ISSUE TITLE
Convert What Can You Do With WordPress Lesson Plan

### ISSUE THREAD

**Issue by jsmcintyre25** [wptrainingteam/what-you-can-do-with-wordpress#2]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [ ]  clean up the Markdown
- [ ]  download the old images
- [ ]  upload the images into GitHub
- [ ]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/what-can-you-do-with-wordpress/
